services:
  redis:
    image: redis:7-alpine
    ports:
      - "63799:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  course-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - .:/app:delegated
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data: 